# Generated by Django 3.2.6 on 2021-08-06 03:41

from django.db import migrations, models
import localflavor.br.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('cpf', localflavor.br.models.BRCPFField(blank=True, max_length=14, unique=True, verbose_name='CPF')),
            ],
        ),
    ]
